# Generated by Django 5.2.14 on 2026-08-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Ad soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Telefon')),
                ('subject', models.CharField(blank=True, max_length=160, verbose_name='Konu')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Gönderim tarihi')),
            ],
            options={
                'verbose_name': 'İletişim mesajı',
                'verbose_name_plural': 'İletişim mesajları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Proje adı')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='URL adı')),
                ('category', models.CharField(default='Mühendislik', max_length=80, verbose_name='Kategori')),
                ('summary', models.CharField(max_length=220, verbose_name='Kısa özet')),
                ('details', models.TextField(blank=True, verbose_name='Proje detayları')),
                ('location', models.CharField(default='Ankara', max_length=100, verbose_name='Lokasyon')),
                ('year', models.PositiveIntegerField(default=2025, verbose_name='Yıl')),
                ('accent', models.CharField(default='#f26a3d', help_text='Örn: #f26a3d', max_length=20, verbose_name='Vurgu rengi')),
                ('is_featured', models.BooleanField(default=True, verbose_name='Ana sayfada göster')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'ordering': ['order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('slug', models.SlugField(max_length=140, unique=True, verbose_name='URL adı')),
                ('short_description', models.CharField(max_length=220, verbose_name='Kısa açıklama')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(default='01', help_text='Kartta görünecek kısa işaret', max_length=3, verbose_name='İkon harfi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yayında')),
            ],
            options={
                'verbose_name': 'Hizmet',
                'verbose_name_plural': 'Hizmetler',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Taşcan Mühendislik', max_length=120, verbose_name='Firma adı')),
                ('tagline', models.CharField(default='Geleceği sağlam temellerle inşa ediyoruz.', max_length=180, verbose_name='Kısa slogan')),
                ('phone', models.CharField(default='+90 312 000 00 00', max_length=40, verbose_name='Telefon')),
                ('email', models.EmailField(default='info@tascanmuhendislik.com', max_length=254, verbose_name='E-posta')),
                ('address', models.CharField(default='Çankaya, Ankara', max_length=240, verbose_name='Adres')),
                ('about_text', models.TextField(default='Taşcan Mühendislik; güvenli, verimli ve sürdürülebilir yapılar için mühendisliği tasarımla buluşturan çözüm ortağınızdır.', verbose_name='Hakkımızda metni')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme tarihi')),
            ],
            options={
                'verbose_name': 'Site ayarları',
                'verbose_name_plural': 'Site ayarları',
            },
        ),
    ]
