# Generated by Django 5.2.14 on 2026-08-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='address',
            field=models.CharField(default='Odunpazarı, Eskişehir', max_length=240, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='info@tascanmuhendislik.com.tr', max_length=254, verbose_name='E-posta'),
        ),
    ]
